services:
  task-test:
    build:
      context: .
    depends_on:
      - db
      - redis
    volumes:
      - .:/var/www/html
  db:
    container_name: task-postgres
    image: postgres:16.0
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 8001:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
  nginx:
    container_name: task-nginx
    build:
      context: ./nginx
    ports:
      - 8080:80
    depends_on:
      - task-test
    volumes:
      - ./public:/var/www/html/public
  redis:
    build:
      context: ./redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
    - redis_data:/var/lib/redis/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_USERNAME: ${REDIS_USERNAME}
volumes:
  dbdata:
  redis_data:
